name: heritage_lens
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  smooth_page_indicator: ^1.2.0+3
  fluid_bottom_nav_bar: ^1.4.0
  image_picker: ^1.1.2
  flutter_tts: ^4.0.2
  permission_handler: ^11.3.1
  connectivity_plus: ^6.0.5
  geolocator: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

